### PR TITLE
Martz modal edit

### LINKED ISSUE #572: Patient-entered medications - update/edit
edit functionality

### LINKED ISSUE #642: Make Modals use their own controllers

### LINKED ISSUE #659: submit medication and close modal
modal currently resets instead of resetting and closing after entering a new medication

### PR DESCRIPTION
**Pull request by oehokie**
- [x] medication edits
- [x] medication deletes
- [x] controller refactor
- [x] jshint / linting
- [x] merge common.js(s)

closes #659 
regarding #656 (jshint stuff)
regarding #650 
closes #642 
regarding #633 
regarding #598 added flag in metadata
closes #572

### CODE REVIEW

**Comment by ekavaliM** [comment]
After uploading blue-button-02, bug in allergies section: 
screen shot 2015-05-20 at 1 03 56 pm

**Comment by ekavaliM** [comment]
The timeline on the record main page now shows when individual entries (allergy, vitals etc) are added as opposed to overall updates to the record (file added, lab received etc). Not necessarily a bug, just different.

**Comment by ekavaliM** [comment]
print my record not working

**Comment by oehokie** [comment]
The allergies bug is weird, because looking at the raw data those fields are blank.  bluebutton-02-updated.xml isn't parsing correctly(?) which is weird because I don't think I touched that.  I changed the timeline to show the individual entries to be consistent with the other sections... in my new branch I'm adding captions to the tooltips that say what category they are.  similarly not sure about print my record because I don't think I touched that either

**Comment by oehokie** [comment]
```
{
    "data": {
        "_id": "555cbf286ead26f23ecfc4e8",
        "metadata": {
            "attribution": [{
                "record": {
                    "_id": "555cbf275ff334f23ea22a5a",
                    "filename": "bluebutton-02-updated.xml"
                },
                "merged": "2015-05-20T17:06:49.054Z",
                "merge_reason": "new"
            }]
        }
    },
    "category": "allergies",
    "metadata": {
        "comments": [],
        "displayDate": "",
        "datetime": [{
            "date": "2015-02-11T00:00:00.000Z",
            "precision": "day",
            "displayDate": "Feb 12, 2015"
        }],
        "starred_comments": 0
    }
},
```

**Comment by kachok** [comment]
README file is outdated (install instructions), probably since client grunt was merged, but need to be updated anyway

**Comment by oehokie** [comment]
Fixed ReadMe comment, allergies bug still exists AFAIK, "all" timeline now includes captions in tooltips for what section it's from, Print issue may be a browser problem

**Pull request merged**
