### PR TITLE
new test files

### PR DESCRIPTION
**Pull request by jsachs**
Nothing much really has to change. bluebutton-01 has some extra vitals in it now. This exercise does make me think that we want a coverage report on the DRE.

### CODE REVIEW

**Comment by ekavaliM** [comment]
Need to copy directory from r1.4 to include updated xml files and a cms file. Also might want to consider changing our medication examples while we're at it.

**Comment by jsachs** [comment]
Do we need a CMS file for the new tests? These test files for explicitly testing CMS are in the `cms`directory. Medication examples might need to change, but the actual mapping tests will be in model/generate libs. We really just need some basic meds for when we start testing E2E with the CRUD API.

**Comment by ekavaliM** [comment]
For demo and benchmarking

**Comment by oehokie** [comment]
Ah see, your tests do the same thing.  Travis passes but if you read the logs they fail.  It's because of the grunt changes

**Comment by jsachs** [comment]
I'm going to close this PR, catch the branch up to 1.5, see if it fixes the tests, then reopen it.

**Pull request closed without merging**
