### PR TITLE
note sorting

### LINKED ISSUE #712: notes date and section sorting don't work
- [x] does not sort by date
- [x] doesn't invert sorting when clicking a second time
- [x] does not sort by section
- [x] doesn't invert sorting

### PR DESCRIPTION
**Pull request by oehokie**
Closes #712
Closes T68

### CODE REVIEW

**Comment by ekavaliM** [comment]
Reverse sorting works for Section Name but not Date. I also agree with Martz that Date sorting is confusing since notes are then sorted within sections as opposed to overall -- I'd advocate for trying to sort them overall by date and maybe get rid of section headers?

**Comment by oehokie** [comment]
I think section sorting is redundant because people can pick what sections to show on the left hand side.  Expanding on @ekavaliM 's comment, I think we should kill section sorting, remove section headers and sort by date only.  Maybe add the appropriate timeline icon to the left to indicate what category the comment is in.  Cross posting on Phab...

**Comment by ekavaliM** [comment]
Timeline needs the anchor dot and should be connected to the vertical line. This is also true for #741 
screen shot 2015-06-04 at 8 47 22 am

**Comment by ekavaliM** [comment]
link back to entry in notes kicks the user back to the login screen

**Comment by oehokie** [comment]
the above comments have been addressed

**Pull request merged**
