### PR TITLE
Martz med modal

### LINKED ISSUE #637: Meds modals don't reset when closed
If you x out of a modal and then click Add Medication again, you're back at the same spot. Might want to reset everything when the modal closes or launches.

### PR DESCRIPTION
**Pull request by oehokie**
Closes #637

### CODE REVIEW

**Comment by ekavaliM** [comment]
grunt isn't passing

**Comment by oehokie** [comment]
grunt passes

**Comment by ekavaliM** [comment]
these tests are still failing: 

  1) Medications API Add (POST):
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:920:16

  2) Medications API GET all:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:920:16

  3) Medications API Edit "before all" hook:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:920:16

  4) Medications API Delete "before all" hook:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:920:16

**Comment by oehokie** [comment]
@ekavaliM uhh... yeah they do.  Are you looking at the right tests?
screen shot 2015-05-13 at 1 22 11 pm

**Comment by jsachs** [comment]
Same issue:

```
  315 passing (46s)
  6 pending
  4 failing

  1) Medications API Add (POST):
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:943:16

  2) Medications API GET all:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:943:16

  3) Medications API Edit "before all" hook:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:943:16

  4) Medications API Delete "before all" hook:
     Error: expected 200 "OK", got 500 "Internal Server Error"
```

**Pull request merged**
